export type Role = 'USER' | 'PROFESSIONAL' | 'SUPPORT_AGENT' | 'ORGANIZATION_ADMIN' | 'CLINICAL_ADVISOR' | 'RESEARCHER' | 'SUPER_ADMIN';

export const Roles = {
  USER: 'USER',
  PROFESSIONAL: 'PROFESSIONAL',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
  ORGANIZATION_ADMIN: 'ORGANIZATION_ADMIN',
  CLINICAL_ADVISOR: 'CLINICAL_ADVISOR',
  RESEARCHER: 'RESEARCHER',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;
